<!-- footer template originally from sw. modified slightly for rawk. -->
<div id="footer">
<div class="right">generated by 
<a href="http://doc.kyleisom.net/p/rawk/">rawk</a> and
<a href="https://pandoc.org/">pandoc</a>, hosted on a
<a href="http://www.prgmr.com/">prgmr vps</a>.<br />
</div>
</script>
</body>
</html>

